source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.3'

# Use mysql as the database for Active Record
gem 'mysql2'

# Use SCSS for stylesheets
gem 'sass-rails', '~> 4.0.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '~> 4.0.0'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 1.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# ページネーション
gem 'kaminari'

# Redis関係
#gem 'redis-store'
#gem 'redis-rails'
gem 'redis-objects'

# 非同期処理
gem 'sidekiq'
gem 'sinatra', require: false
gem 'slim'

# 並列処理
gem 'parallel'

# commpass
gem 'compass'

# JSONの高速なパーサー
gem 'yajl-ruby'

# HTML/XMLパーサー
gem 'nokogiri'

# railsのconfigを設定できる
gem 'rails_config'

# データベースに初期値を入れる
# ex) db/fixtures/users.rb
# rake db:seed_fu
gem 'seed-fu', github: 'mbleigh/seed-fu'

# unsignedを使えるようにする
gem 'activerecord-mysql-unsigned'

# BULK INSERTをできるようにする
gem 'activerecord-import'

# APIドキュメントを作成するツール
gem 'apipie-rails'
gem 'maruku'

# A/Bテストができるようになる
gem 'split'

# バッチ処理ができるようになる
gem 'whenever', :require => false

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.1.2'

# Use unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]
group :development do
  # エラー画面をわかりやすく整形してくれる
  gem 'better_errors'

  # better_errorsの画面上にirb/pry(PERL)を表示する
  gem 'binding_of_caller'

  # クエリの速度を表示する
  gem 'rack-mini-profiler', '0.9.0.pre'

  # 非効率的なクエリの検出
  gem 'bullet'
end

group :test, :development do
  gem 'pry-rails'
  gem 'pry-doc'
  gem 'pry-stack_explorer'

  if RUBY_VERSION >= '2.0.0'
    gem 'pry-byebug'
  else
    # 以下はRuby1.9の時のみ使う(pry-byebugの代わりに)
    # debuggerは1.9以下でしか動作しない, remote は byebug で使えないようになった
    gem 'pry-debugger'
    gem 'pry-remote'
  end

  gem 'better_errors'
  gem 'binding_of_caller'

  gem 'hirb'
  gem 'hirb-unicode'

  gem 'tapp'
  gem 'awesome_print'
  gem 'quiet_assets'
  gem 'annotate', git: 'git://github.com/ctran/annotate_models.git'
  gem 'timecop'
  gem 'rspec-rails'
  gem 'guard-rspec'
  gem 'factory_girl_rails'
  gem 'database_rewinder'


  gem 'capistrano', '~> 3.0.1', require: false
  gem 'capistrano-bundler', require: false
  gem 'capistrano-rails'
  gem 'capistrano-sidekiq'
end

# use test
gem 'rspec-rails'
gem 'factory_girl_rails'