development:
  host: localhost
  port: 6379
  password:
  expires_in:
  namespace: Pornofolio

test:
  host: localhost
  port: 6379
  password:
  expires_in:
  namespace: Pornofolio

production:
  host: localhost
  port: 6379
  password:
  expires_in:
  namespace: Pornofolio