cors:
  development:
    headers:
      'Access-Control-Expose-Headers': 'ETag'
      'Access-Control-Allow-Methods': 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
      'Access-Control-Allow-Headers': '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match,Auth-User-Token'
      'Access-Control-Max-Age': '86400'
      'Access-Control-Allow-Credentials': 'true'
      'Access-Control-Request-Method': '*'
  production:
    headers:
      'Access-Control-Expose-Headers': 'ETag'
      'Access-Control-Allow-Methods': 'GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD'
      'Access-Control-Allow-Headers': '*,x-requested-with,Content-Type,If-Modified-Since,If-None-Match,Auth-User-Token'
      'Access-Control-Max-Age': '86400'
      'Access-Control-Allow-Credentials': 'true'
      'Access-Control-Request-Method': '*'
  test:
      headers: